export {
  DocsService,
  createDocsService,
  type CreatePageInput,
  type CreatePageVersionInput,
  type CreateSpaceInput,
  type DocsServiceDb,
  type GetPageInput,
  type ListVersionsInput,
  type ListSpacesInput,
  type MovePageInput,
  type PageMetadata,
  type PageTreeNode,
  type PageVersionMetadata,
  type ReorderPageInput,
  type RenamePageInput,
  type RenameSpaceInput,
  type SoftDeletePageInput,
  type RestorePageVersionInput,
  type SoftDeleteSpaceInput,
  type VersionRestoreResult,
} from "./service.js";
