#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const TOKENS_PATH = path.join(process.cwd(), "packages/ui/tokens/tokens.json");
const CSS_OUT_PATH = path.join(process.cwd(), "packages/ui/tokens/tokens.css");
const TAILWIND_OUT_PATH = path.join(process.cwd(), "packages/ui/tokens/tailwind-preset.ts");

function readTokens() {
  return JSON.parse(fs.readFileSync(TOKENS_PATH, "utf8"));
}

function toCssVars(themeTokens) {
  return Object.entries(themeTokens)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");
}

function buildCss(tokens) {
  return [
    "/* Generated by scripts/build-tokens.js. Do not edit by hand. */",
    ":root {",
    toCssVars(tokens.light ?? {}),
    "}",
    "",
    ".dark {",
    toCssVars(tokens.dark ?? {}),
    "}",
    "",
  ].join("\n");
}

function buildTailwindPreset(tokens) {
  const names = Object.keys({ ...(tokens.light ?? {}), ...(tokens.dark ?? {}) }).sort();
  const colorLines = names.map((name) => `        "${name}": "var(--${name})",`);

  return [
    "/* Generated by scripts/build-tokens.js. Do not edit by hand. */",
    "",
    "const preset = {",
    "  theme: {",
    "    extend: {",
    "      colors: {",
    ...colorLines,
    "      },",
    "    },",
    "  },",
    "};",
    "",
    "export default preset;",
    "",
  ].join("\n");
}

const tokens = readTokens();

fs.mkdirSync(path.dirname(CSS_OUT_PATH), { recursive: true });
fs.writeFileSync(CSS_OUT_PATH, buildCss(tokens));
fs.writeFileSync(TAILWIND_OUT_PATH, buildTailwindPreset(tokens));

console.log(`Generated ${CSS_OUT_PATH}`);
console.log(`Generated ${TAILWIND_OUT_PATH}`);
