/* Generated by scripts/build-tokens.js. Do not edit by hand. */

const preset = {
  theme: {
    extend: {
      colors: {
        "accent": "var(--accent)",
        "accent-fg": "var(--accent-fg)",
        "accent-strong": "var(--accent-strong)",
        "accent-subtle": "var(--accent-subtle)",
        "accent-subtle-border": "var(--accent-subtle-border)",
        "border": "var(--border)",
        "border-catalog": "var(--border-catalog)",
        "border-control": "var(--border-control)",
        "border-muted": "var(--border-muted)",
        "border-strong": "var(--border-strong)",
        "border-subtle": "var(--border-subtle)",
        "finance-negative": "var(--finance-negative)",
        "finance-negative-strong": "var(--finance-negative-strong)",
        "finance-neutral": "var(--finance-neutral)",
        "finance-positive": "var(--finance-positive)",
        "finance-positive-strong": "var(--finance-positive-strong)",
        "finance-warning": "var(--finance-warning)",
        "focus-ring": "var(--focus-ring)",
        "skeleton": "var(--skeleton)",
        "skeleton-muted": "var(--skeleton-muted)",
        "skeleton-strong": "var(--skeleton-strong)",
        "status-approved": "var(--status-approved)",
        "status-done": "var(--status-done)",
        "status-pending": "var(--status-pending)",
        "status-pending-bg": "var(--status-pending-bg)",
        "status-pending-border": "var(--status-pending-border)",
        "status-rejected": "var(--status-rejected)",
        "surface-1": "var(--surface-1)",
        "surface-2": "var(--surface-2)",
        "surface-3": "var(--surface-3)",
        "surface-control": "var(--surface-control)",
        "surface-muted": "var(--surface-muted)",
        "text-muted": "var(--text-muted)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
      },
    },
  },
};

export default preset;
